### ISSUE TITLE
Submitted the generated transaction, now what?

### ISSUE THREAD

**Issue by alex-grover** [ZKsync-Association/zknation-data#15]
Hello! I followed the instructions in this repo and executed the generated transaction from my mainnet Gnosis Safe. I see that the airdrop claim went through on L2, but it's to an address that I don't own. It seems like that might be an address I can control by submitting a crosschain tx, but I'm unsure how to do that.

Could you please advise what the expected next steps are after following the instructions in this repo? Thanks in advance!

**Comment by d-roak** [comment]
+1, same happened on my side with the same Gnosis Safe setup

**Comment by vladbochok** [comment]
Hey @alex-grover @d-roak, 

The instructions in the repo contain two steps flow for L1 smart contracts claim:
1. Claiming tokens
- https://github.com/ZKsync-Association/zknation-data?tab=readme-ov-file#1-claim-tokens-transaction
2. Sending tokens to another address (e.g. L2 native)
- https://github.com/ZKsync-Association/zknation-data?tab=readme-ov-file#2-transfer-tokens-to-the-specified-address-transaction

Please follow the second step to send tokens to the specified address.

**Comment by alex-grover** [comment]
it worked! Thank you so much 🙏
